title: Alec Glisman # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b> Links: </b> <br \>
  <b> &emsp; </b> <a href="https://www.che.caltech.edu/groups/jfb/index.html">Brady Group</a>  <br />
  <b> &emsp; </b> <a href="https://github.com/alec-glisman">GitHub</a>  <br />
  <b> &emsp; </b> <a href="https://www.linkedin.com/in/alec-glisman">LinkedIn</a>  <br />
  <b> &emsp; </b> <a href="https://scholar.google.com/citations?user=wGifpRQAAAAJ&hl=en">Google Scholar</a>  <br />
  <b> &emsp; </b> <a href="https://www.researchgate.net/profile/Alec_Glisman">Research Gate</a>  <br />
  <b> &emsp; </b> <a href="https://arxiv.org/search/cond-mat?searchtype=author&query=Glisman%2C+A">arXiv</a>  <br />
  <b> &emsp; </b> <a href="https://orcid.org/0000-0001-9677-1958">ORCID</a>   <br />
  
theme: jekyll-theme-minimal
google_analytics: G-44Y2BY3P2N
